[package]
name = "kkameokda"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
crossterm = "0.20"
color-eyre = "0.6.3"
rand = "0.8.5"
dirs = "5.0.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5.23", features = ["derive"] }
